package org.autorepair.data.exceptions

class UnathorizedException: Throwable(message = "no auth")